version: "3.9"

services:
  app:
    build: .
    container_name: wedding-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000

